### PR TITLE
Created css class for no-informationen

### PR DESCRIPTION
**Pull request by vanditasharma**
For #50 

CSS class when informationen not available

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Thanks for submitting this.

I think, throughout the project, we use the functions like this to show and hide information:
```
hideById('header-info');
showById('left-side');
```

**Comment by niccokunzmann** [comment]
There is no ["no-information" tag](https://github.com/gruener-campus-malchow/vertretungsplan/search?q=information&type=Code&utf8=%E2%9C%93) in the code. I think, this would have been useful to hide and show tags in the context of the closed issue #50. but is applicable not any more.

You actually solved the issue #50 just by commenting. What would you like to do with the code? What are your thoughts?

**Comment by niccokunzmann** [comment]
And you are right, there should have been comments about the solution pull-request in #50 :)

**Comment by nicolasraube** [comment]
Thank you for participating! I will look into the request as well in the following days.

**Comment by nicolasraube** [comment]
Sorry for letting you wait this long.
I don't think this would be a good change. As @niccokunzmann said, it gets hidden by the hideById(e) function which adds a 'hidden' class to the element.
Please let me know if I misunderstood something. We appreciate your contribution.

**Pull request closed without merging**
